name: count_habits
description: "Fourth App Project Produced by Kolbe"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  pedantic_mono: ^1.24.0+1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  fonts:
    - family: Monomaniac_One
      fonts:
        - asset: assets/fonts/Monomaniac_One/MonomaniacOne-Regular.ttf
    - family: Hachi_Maru_Pop
      fonts:
        - asset: assets/fonts/Hachi_Maru_Pop/HachiMaruPop-Regular.ttf
  uses-material-design: true
