name: count_habits
description: "Fourth App Project Produced by Kolbe"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  lottie: ^3.0.0
  pedantic_mono: ^1.24.0+1
  riverpod_annotation: ^2.3.3
  riverpod_generator: ^2.3.9
  shared_preferences: ^2.2.2
  uuid: ^4.3.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.24.9

flutter:
  assets:
    - assets/animation/spark.json
    - assets/animation/square.json
  fonts:
    - family: Monomaniac_One
      fonts:
        - asset: assets/fonts/Monomaniac_One/MonomaniacOne-Regular.ttf
    - family: Hachi_Maru_Pop
      fonts:
        - asset: assets/fonts/Hachi_Maru_Pop/HachiMaruPop-Regular.ttf
  uses-material-design: true
