name: count_habits
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Monomaniac_One
      fonts:
        - asset: assets/fonts/Monomaniac_One/MonomaniacOne-Regular.ttf
    - family: Hachi_Maru_Pop
      fonts:
        - asset: assets/fonts/Hachi_Maru_Pop/HachiMaruPop-Regular.ttf
  uses-material-design: true
