name: Build, Analytics, Unit, Widget Test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
 lint_and_test:
  # ローカルのOSと一致させないとGoldenTestで微妙なレイアウトのズレが発生し、テストに失敗する
  runs-on: macos-latest
  steps:
   - uses: actions/checkout@v3
   - uses: subosito/flutter-action@v2.3.0
     with:
      flutter-version: '3.16.8'
   - name: Install packages
     run: flutter pub get
   - name: Unit Test
     run: flutter test
   - name: flutter analyze
     run: flutter analyze > flutter_analyze_report.txt
      
   - name: setup ruby
     if: ${{ failure() }}
     uses: ruby/setup-ruby@v1
     with:
       ruby-version: 3.2
       bundler-cache: true
        
   - name: run danger
     if: ${{ failure() }}
     uses: MeilCli/danger-action@v5.6.3
     with:
       plugins_file: Gemfile
       danger_file: Dangerfile
       danger_id: danger-pr
     env:
       DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_TOKEN }}