name: Build, Analytics, Unit, Widget Test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
jobs:
 lint_and_test:
  # ローカルのOSと一致させないとGoldenTestで微妙なレイアウトのズレが発生し、テストに失敗する
  runs-on: macos-latest
  steps:
   - uses: actions/checkout@v3
   - uses: subosito/flutter-action@v2.3.0
     with:
      flutter-version: '3.16.8'
   - name: Install packages
     run: flutter pub get
   - name: Unit Test
     run: flutter test
   - name: flutter analyze
     run: flutter analyze